apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello-server
  name: hello-server
spec:
  containers:
  - image: ko://github.com/ericsmalling/ko-demo
    name: hello-server
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
